export const routeKeys = {
    home: "/",
    signIn: "/sign-in",
    forgotPassword: "/auth/forgot-password",
    documentation: "/documentation",
    coffeeShop: "/coffee-shop",
    coffeeShopHome: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}`,
    employees: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/employees`,
    dailyReports: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/daily-reports`,
    expenseReports: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/expense-reports`,
    facilityExpenses: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/facility-expenses`,
    inventoryAudits: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/inventory-audits`,
    ownerWithdrawals: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/owner-withdrawals`,
    kavappInventory: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/kavapp-inventory`,
    kavappInventoryAlertRules: (coffeeShopId: string) =>
        `/coffee-shop/${coffeeShopId}/kavapp-inventory/alert-rules`,
    dashboard: (coffeeShopId: string) => `/coffee-shop/${coffeeShopId}/dashboard`,
    settings: "/settings",
    workspaceSettings: "/settings/workspace",
    coffeeShopsSettings: "/settings/coffee-shops",
    profileSettings: "/settings/profile",
    plan: "/onboarding/plan",
} as const;
