export const routeKeys = {
    home: "",
    signIn: "/sign-in",
    forgotPassword: "/auth/forgot-password",
    documentation: "/documentation",
    coffeeShop: "/coffee-shop",
    employees: "/coffee-shop/employees",
    dailyReports: "/coffee-shop/daily-reports",
    expenseReports: "/coffee-shop/expense-reports",
    inventoryAudits: "/coffee-shop/inventory-audits",
    facilityExpenses: "/coffee-shop/facility-expenses",
    ownerWithdrawals: "/coffee-shop/owner-withdrawals",
    kavappInventory: "/coffee-shop/kavapp-inventory",
    kavappInventoryAlertRules: "/coffee-shop/kavapp-inventory/alert-rules",
    workspaceSettings: "/settings/workspace",
    profileSettings: "/settings/profile",
    plan: "/onboarding/plan",
} as const;
